#-------------------------------------------------------------------------------
#
#     bufpool library build construction script
#
import os

#-------------------------------------------------------------------------------
#
#     General
#
ProductName = 'bufpool'

Import('env')

env = env.Clone()
Platform = env['PLATFORM']

#-------------------------------------------------------------------------------
#
#     Setup sources and target
#
Sources = ['BufPool.cpp']
Target  = os.path.join(env['LIBPATH'], ProductName)

#-------------------------------------------------------------------------------
#
#     Setup local construction environment
#
env.EnableQt5Modules(['QtTest', 'QtCore'])

DEFINES = ['ENA_FW_QT', 'MSG_SELF_RELEASE']

if Platform == 'win32':
    DEFINES += ['ENA_WIN_API']

env.Append(CCFLAGS = ['-D'+ d for d in DEFINES] )

#-------------------------------------------------------------------------------
#
#     Build the target
#

lib = env.StaticLibrary(Target, Sources)

#-------------------------------------------------------------------------------

